//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3System.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A3System.Resources.ErrorTranslation", typeof(ErrorTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na criação de cargos..
        /// </summary>
        public static string CargoCreateFailed {
            get {
                return ResourceManager.GetString("CargoCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de cargo não preenchido..
        /// </summary>
        public static string CargoNameNull {
            get {
                return ResourceManager.GetString("CargoNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo não preenchido..
        /// </summary>
        public static string CargoNotFilled {
            get {
                return ResourceManager.GetString("CargoNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não fora encontrado(s) o(s) Cargo(s)..
        /// </summary>
        public static string CargoNotFound {
            get {
                return ResourceManager.GetString("CargoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não fora encontrado o Cargo com ID: {0}..
        /// </summary>
        public static string CargoNotFoundID0 {
            get {
                return ResourceManager.GetString("CargoNotFoundID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao fazer envio de email..
        /// </summary>
        public static string EmailSendError {
            get {
                return ResourceManager.GetString("EmailSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário não preenchido corretamente..
        /// </summary>
        public static string FormNotFilled {
            get {
                return ResourceManager.GetString("FormNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo informado é inválido..
        /// </summary>
        public static string InvalidCargo {
            get {
                return ResourceManager.GetString("InvalidCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão Chamados Inválida..
        /// </summary>
        public static string InvalidPermissaoChamados {
            get {
                return ResourceManager.GetString("InvalidPermissaoChamados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão Metas Inválida..
        /// </summary>
        public static string InvalidPermissaoMetas {
            get {
                return ResourceManager.GetString("InvalidPermissaoMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor Inválido..
        /// </summary>
        public static string InvalidSetor {
            get {
                return ResourceManager.GetString("InvalidSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token informado é inválido..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email de usuário inválido, o email deve ser nome.sobrenome..
        /// </summary>
        public static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Inválida..
        /// </summary>
        public static string InvalidVertical {
            get {
                return ResourceManager.GetString("InvalidVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encotrado nenhum Log com ErrorCode: {0}..
        /// </summary>
        public static string LogCodeInvalid0 {
            get {
                return ResourceManager.GetString("LogCodeInvalid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao cadastrar Log..
        /// </summary>
        public static string LogErrorCreate {
            get {
                return ResourceManager.GetString("LogErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao buscar Log..
        /// </summary>
        public static string LogErrorRead {
            get {
                return ResourceManager.GetString("LogErrorRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum Log com id: {0}..
        /// </summary>
        public static string LogIdInvalid0 {
            get {
                return ResourceManager.GetString("LogIdInvalid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha no login, Email ou Senha estão vazios..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum Log..
        /// </summary>
        public static string LogNotFound {
            get {
                return ResourceManager.GetString("LogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout falhou..
        /// </summary>
        public static string LogoutFailed {
            get {
                return ResourceManager.GetString("LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas não são as mesmas..
        /// </summary>
        public static string PasswordDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não preenchida..
        /// </summary>
        public static string PasswordNotFilled {
            get {
                return ResourceManager.GetString("PasswordNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar departamento e permissão.
        /// </summary>
        public static string PermissaoChamadoFailedUpdate {
            get {
                return ResourceManager.GetString("PermissaoChamadoFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado a Permissão Chamado..
        /// </summary>
        public static string PermissaoChamadoNotFound {
            get {
                return ResourceManager.GetString("PermissaoChamadoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao cadastrar departamento e permissão..
        /// </summary>
        public static string PermissaoChamadosFailedRegister {
            get {
                return ResourceManager.GetString("PermissaoChamadosFailedRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão inválida para Permissão Chamados..
        /// </summary>
        public static string PermissaoChamadosPermissaoInvalid {
            get {
                return ResourceManager.GetString("PermissaoChamadosPermissaoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor inválido para Permissão Chamados..
        /// </summary>
        public static string PermissaoChamadosSetorInvalid {
            get {
                return ResourceManager.GetString("PermissaoChamadosSetorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido para Permissão Chamados..
        /// </summary>
        public static string PermissaoChamadosStatusInvalid {
            get {
                return ResourceManager.GetString("PermissaoChamadosStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido para Permissão Chamados..
        /// </summary>
        public static string PermissaoChamadosUserInvalid {
            get {
                return ResourceManager.GetString("PermissaoChamadosUserInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao criar Permissão Metas..
        /// </summary>
        public static string PermissaoMetasFailedCreate {
            get {
                return ResourceManager.GetString("PermissaoMetasFailedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar Permissão Metas..
        /// </summary>
        public static string PermissaoMetasFailedUpdate {
            get {
                return ResourceManager.GetString("PermissaoMetasFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome inválido para Permissões Metas..
        /// </summary>
        public static string PermissaoMetasNameInvalid {
            get {
                return ResourceManager.GetString("PermissaoMetasNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado Permissão Metas..
        /// </summary>
        public static string PermissaoMetasNotFound {
            get {
                return ResourceManager.GetString("PermissaoMetasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão Metas não encontrada o ID: {0}..
        /// </summary>
        public static string PermissaoMetasNotFoundID0 {
            get {
                return ResourceManager.GetString("PermissaoMetasNotFoundID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão Metas não encontrada para o Usuário de ID: {0}.
        /// </summary>
        public static string PermissaoMetasNotFoundUserId0 {
            get {
                return ResourceManager.GetString("PermissaoMetasNotFoundUserId0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de recuperação inválido..
        /// </summary>
        public static string RecoverCodeInvalid {
            get {
                return ResourceManager.GetString("RecoverCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualização de status do Setor não pode ser concluida pois o campo não foi preenchido..
        ///   Looks up a localized string similar to Atualização de status do Setor não pode ser concluida pois o campo não foi preenchido..
        /// </summary>
        public static string SetorActiveError {
            get {
                return ResourceManager.GetString("SetorActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na criação de setor..
        /// </summary>
        public static string SetorCreateFailed {
            get {
                return ResourceManager.GetString("SetorCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar Setor..
        /// </summary>
        public static string SetorFailedUpdate {
            get {
                return ResourceManager.GetString("SetorFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de setor não preenchido..
        /// </summary>
        public static string SetorNameNull {
            get {
                return ResourceManager.GetString("SetorNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor não preenchido..
        /// </summary>
        public static string SetorNotFilled {
            get {
                return ResourceManager.GetString("SetorNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não fora encontrado(s) o(s) setor(es)..
        /// </summary>
        public static string SetorNotFound {
            get {
                return ResourceManager.GetString("SetorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não fora encontrado o setor com ID: {0}..
        /// </summary>
        public static string SetorNotFoundID0 {
            get {
                return ResourceManager.GetString("SetorNotFoundID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleção de Token falhou..
        /// </summary>
        public static string TokenDeleteFailed {
            get {
                return ResourceManager.GetString("TokenDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validação de Token falhou..
        /// </summary>
        public static string TokenValidationFailed {
            get {
                return ResourceManager.GetString("TokenValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na criação de usuário..
        /// </summary>
        public static string UserCreateFailed {
            get {
                return ResourceManager.GetString("UserCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este email não esta cadastrado..
        /// </summary>
        public static string UserEmailDoenstExist {
            get {
                return ResourceManager.GetString("UserEmailDoenstExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email de usuário não foi preenchido..
        /// </summary>
        public static string UserEmailNotFilled {
            get {
                return ResourceManager.GetString("UserEmailNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ja foi cadastrado..
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao cadastrar usuário..
        /// </summary>
        public static string UserFailedRegister {
            get {
                return ResourceManager.GetString("UserFailedRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não foi encontrado..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não foi encontrado para a Vertical Id: {0}..
        /// </summary>
        public static string UserNotFoundVertical0 {
            get {
                return ResourceManager.GetString("UserNotFoundVertical0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não possui autorização..
        /// </summary>
        public static string UserUnhauthorized {
            get {
                return ResourceManager.GetString("UserUnhauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na atualização de usuário..
        /// </summary>
        public static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na criação de vertical..
        /// </summary>
        public static string VerticalCreateFailed {
            get {
                return ResourceManager.GetString("VerticalCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da vertical não preechida..
        /// </summary>
        public static string VerticalNameNull {
            get {
                return ResourceManager.GetString("VerticalNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical não foi encontrada..
        /// </summary>
        public static string VerticalNotFound {
            get {
                return ResourceManager.GetString("VerticalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na atualização de Vertical..
        /// </summary>
        public static string VerticalUpdateFailed {
            get {
                return ResourceManager.GetString("VerticalUpdateFailed", resourceCulture);
            }
        }
    }
}
