//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3System.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SucessTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SucessTranslation() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A3System.Resources.SucessTranslation", typeof(SucessTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo(s) criado(s) com sucesso..
        /// </summary>
        public static string CargoCreate {
            get {
                return ResourceManager.GetString("CargoCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo atualizado com sucesso..
        /// </summary>
        public static string CargoUpdate {
            get {
                return ResourceManager.GetString("CargoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email enviado!.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão(ões) Chamados cadatrada(s) com sucesso..
        /// </summary>
        public static string PermissaoChamadosRegistered {
            get {
                return ResourceManager.GetString("PermissaoChamadosRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão Chamados atualizada com sucesso para User ID: {0}..
        /// </summary>
        public static string PermissaoChamadosUpdated0 {
            get {
                return ResourceManager.GetString("PermissaoChamadosUpdated0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão(ões) Metas cadastrada(s) com sucesso..
        /// </summary>
        public static string PermissaoMetasRegistered {
            get {
                return ResourceManager.GetString("PermissaoMetasRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão Metas atualizada com sucesso..
        /// </summary>
        public static string PermissaoMetasUpdated {
            get {
                return ResourceManager.GetString("PermissaoMetasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setor(es) cadastrado(s) com sucesso..
        /// </summary>
        public static string SetorRegistered {
            get {
                return ResourceManager.GetString("SetorRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setor atualizado com sucesso..
        /// </summary>
        public static string SetorUpdated {
            get {
                return ResourceManager.GetString("SetorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email de usuário atualizada com sucesso para {0}, atualização para User ID: {1}..
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserEmailUpdatedEmail0ID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha de usuário atualizada com sucesso..
        /// </summary>
        public static string UserPasswordUpdated {
            get {
                return ResourceManager.GetString("UserPasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão Chamados atualizada com sucesso para User ID: {0}..
        /// </summary>
        public static string UserPermissaoChamadosID0 {
            get {
                return ResourceManager.GetString("UserPermissaoChamadosID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário cadastrado com sucesso..
        /// </summary>
        public static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setor/Cargo atualizada com sucesso para User ID: {0}..
        /// </summary>
        public static string UserSetorCargoUpdatedID0 {
            get {
                return ResourceManager.GetString("UserSetorCargoUpdatedID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vertical/Permissão Metas atualizada com sucesso para User ID: {0}..
        /// </summary>
        public static string UserVeticalPermissaoMetasUpdatedID0 {
            get {
                return ResourceManager.GetString("UserVeticalPermissaoMetasUpdatedID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vertical(is) cadastrada(s) com sucesso..
        /// </summary>
        public static string VerticalRegistered {
            get {
                return ResourceManager.GetString("VerticalRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vertical atualizada com sucesso..
        /// </summary>
        public static string VerticalUpdated {
            get {
                return ResourceManager.GetString("VerticalUpdated", resourceCulture);
            }
        }
    }
}
